# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "^swagger.json$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt-repo
  - repo: https://github.com/muya/swaggo-hooks
    rev: v1.1.1
    hooks:
      - id: swag-fmt
  - repo: https://github.com/kamadorueda/alejandra
    rev: 3.0.0
    hooks:
      - id: alejandra-system
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: swag
        name: Generate Swagger documentation
        entry: make swag
        language: system
        files: \.go$
        pass_filenames: false
